// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jehfvcoxteqktaupchzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplaGZ2Y294dGVxa3RhdXBjaHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDY4NjcsImV4cCI6MjA2OTk4Mjg2N30.spP_uK3dnHdpj6zbj_MAhnKCTrI21nykValBE9DmUEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});